### ISSUE TITLE
TIMING support like `eslint`?

### ISSUE THREAD

**Issue by JounQin** [remarkjs/remark-lint#293] opened 2022-07-26 03:06 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to figure out which rule is the slowest one.

### Solution

Add `TIMING` env support

<img width="500" alt="企业微信截图_2de8b34d-93d2-481f-962e-a87439e61e01" src="https://user-images.githubusercontent.com/8336744/180914495-38dbf6d8-4706-4f81-9c8d-827afd226972.png">

### Alternatives

N/A

**Comment by wooorm** [comment] 2022-07-26 09:00
There are probably a lot of different ways to solve this. Depending on what your goals are.

It’s different for unified though, because it has plugins which do arbitrary things, and eslint only has rules, which all have names.

What do you measure? The plugin as a whole (“attacher”) is a function that gets called, and could do a ton of sync work.
But you probably mean the transformer (the thing that inspects/transforms trees)?

Deep down, those are all called here: https://github.com/wooorm/trough/blob/0b392bf2ed11dba640dac9298a74b086f4bd699c/index.js#L27. That’s very far from the info you are looking for.

Perhaps the easier: make your own time plugin:

```js
unified()
  .use(createMyTimePlugin('label 1'))
  .use(somePlugin)
  .use(createMyTimePlugin('label 2'))
  .use(somePlugin)
  .use(createMyTimePlugin('label 2'))
```

```js
export default function createMyTimePlugin(name) {
  return plugin
  function plugin() {
    return (_, file) {
       let now = Date.now();
       // ...
       file.data.performanceInfo = {...file.data.performanceInfo, ...stuff}
    }
  }
}
```

And then finally, you get the `file` out of unified, which now has metadata added to it.

**Comment by JounQin** [comment] 2022-07-26 09:53
> Perhaps the easier: make your own time plugin:

My goal is to perf all plugins easily, for example a cli only flag, your proposed solution seems not quite *easily*. 🤣

**Comment by wooorm** [comment] 2022-07-26 10:39
> My goal is to perf all plugins easily

This is currently impossible, unless with my above idea.

---

The problem is that the CLI has no real knowledge of transformers, or remark-lint rules.
If you are interested in CLI flag, it would likely work according to my above suggestion. But there are still many open questions. E.g., how to deal with presets?

**Comment by JounQin** [comment] 2022-07-26 10:45
Do you think this is a good-to-have feature or out-of-scope instead? So that we can decide whether or not to offer efforts into this?

**Comment by wooorm** [comment] 2022-07-31 18:27
If there is a good way to add it, sure, that’s acceptable.
But I’m not sure there is a good way.

Perhaps it is also possible to make this into a thing that does not depend on `unified-engine`. So that it can work with `unified` itself, everywhere?

**Comment by wooorm** [comment] 2023-10-27 16:20
@JounQin I don’t really know how to solve this on this level.
If you want to check how a plugin is doing, perhaps that’s just better done manually with a plugin that runs before/after it?
It’s not that this is a bad idea, but, it could be anywhere, doesn’t have to be here? Plugins should often focus on being fast themselves?

Do you mind if I close this?

**Comment by JounQin** [comment] 2023-10-27 22:32
Free to close. 👍

**Closed** 2023-10-28 06:56 UTC
Labels: 🤞 phase/open
