### ISSUE TITLE
Option to Fix References

### ISSUE THREAD

**Issue by samjcombs** [remarkjs/remark-lint#306] opened 2023-02-05 16:09 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It would be great if these three rules: 
- `no-undefined-references`
- `no-duplicate-definitions`
- `no-unused-definitions`
had a `--fix` or `--output` option to do the following:
- `no-undefined-references` - remove the brackets around the undefined reference
- `no-duplicate-definitions` - add a comment to each duplicate so the user can decide which one to keep
- `no-unused-definitions` - remove the definition entirely

I have been looking into how to achieve this but before I dive in completely I was wondering if theres a simple option to turn a rule into a write rule instead of just a warning reporter. 

Great work on this repo, very impressive stuff here!

### For `no-undefined-references`

Given this input:
```markdown
Welcome to [foo].
```
Desired output:
```markdown
Welcome to foo.
```

### For `no-duplicate-definitions` 

Given this input:
```markdown
Welcome to [foo].
[foo]: http://foo.com/1
[foo]: http://foo.com/2
```
Desired output:
```markdown
Welcome to [foo].
[foo]: http://foo.com/1 // Duplicate definition `foo` defined on line 3. 
[foo]: http://foo.com/2 // Duplicate definition `foo` defined on line 2. 
```

### For `no-unused-definitions`

Given this input:
```markdown
Welcome to foo.
[bar]: http://foo.com/1
```
Desired output:
```markdown
Welcome to foo.
```

### Alternatives

I tried piping the output of the cli with these three rules enabled to a script that would parse it and determine where to do file edits, but it got too complicated as lots of work has to be done to make sure that when it starts editing the file, future edits take into account what was already removed and translate positions of everything accordingly.  All in all, not a good solution.  

Another option I've been toying with is to use these rules to output the AST tree instead of the files, and then parse through that AST and perform the modifications, but I'm not sure how I'd find the violating AST nodes, unless these rules actually add `isAllowed` to the ast nodes themselves.  

Open to other solutions here and it may be easier to do this on a rule by rule basis. 

But an abstract solution to provide a `fix` and `fix options` for each rule would be great, so users could say, for nodes that violate this rule, fix it in this way.  

Thanks much!

**Comment by ChristianMurphy** [comment] 2023-02-05 19:24
> I have been looking into how to achieve this but before I dive in completely I was wondering if theres a simple option to turn a rule into a write rule instead of just a warning reporter.

Not currently, see https://github.com/remarkjs/remark-lint/issues/82

> no-undefined-references
> no-unused-definitions

I'd be cautious outright removing the reference or definitions as a fix.
I see there being (at least) three cases.
1. There is plain text with a parenthetical which happens to use square brackets, the appropriate fix here would be to escape to clarify that it cannot be a reference (`[aside]` becomes `\[aside\]`)
2. There a reference is intended but there is a typo (`[a-real-reference-oops]` should suggest, "reference is undefined did you mean `[a-real-reference]`?")
3. Definition was intentionally removed, but a reference is still hanging (the situation you note)

Given that there are multiple scenarios, I'm not sure `remark-lint` should take automatic action even if it could.
This feels like something where an integration with https://github.com/remarkjs/vscode-remark would be a better fit, allowing the user to choose from a list of potential fixes.

> no-duplicate-definitions

I'm not sure the value of adding a comment would have here.
It doesn't fix the error, and it contains the same information an error message would have.
So the error message may be fine?

**Comment by ChristianMurphy** [comment] 2023-02-08 19:27
@samjcombs thoughts on the above? Is thing something you'd be interested in working on?

**Comment by remcohaszing** [comment] 2023-02-09 09:51
[`remark-language-server`](https://github.com/remarkjs/remark-language-server) / [`vscode-remark`](https://github.com/remarkjs/vscode-remark) gives suggestions based on the `expected` property of reported messages. Let’s say you have this message, it will show a quick fix suggestion to remove the reference:

```js
const message = new VFileMessage('Undefined reference [foo]', nodeOrPosition, 'remark-lint:no-undefined-references')
message.expected = ['foo']
```

For removal, suggest an empty string.

```js
const message = new VFileMessage('Duplicate reference [foo]', nodeOrPosition, 'remark-lint:no-duplicate-definitions')
message.expected = ['']
```

This `expected` property is provided by quite a lot of `retext` plugins, but not `remark-lint` plugins. I definitely see value to add several of those.

This doesn’t provide an option to fix all issues with a single command though.

**Comment by wooorm** [comment] 2024-01-19 16:45
Closing as is discussed in GH-82.

Adding `actual`/`expected` fields can be done in separately PRs!

**Comment by wooorm** [comment] 2024-01-19 16:45
Duplicate of #82

**Closed by wooorm** 2024-01-19 16:45 UTC
Labels: 🤞 phase/open
